### ISSUE TITLE
`fmt` plugin not in plugins.html

### ISSUE THREAD

**Issue by joshuarli** [micro-editor/micro-editor.github.io#6]
@sum01 The `fmt` plugin isn't on [`plugins.html`](https://micro-editor.github.io/plugins.html), but is present on the official [`channel.json`](https://raw.githubusercontent.com/micro-editor/plugin-channel/master/channel.json).

![image](https://user-images.githubusercontent.com/14209781/36947957-46535b10-1fa1-11e8-9cd7-4fb4d2191c70.png)

**Comment by sum01** [comment]
I don't think that list is hard-coded. Probably something wrong with the JS. Maybe in https://github.com/micro-editor/micro-editor.github.io/blob/master/micro_files/plugin-search.js ?

**Comment by joshuarli** [comment]
Yeah, that's what I meant by being present in `channel.json`, because that is fetched via AJAX. So probably something wrong with the js.

**Comment by sum01** [comment]
No idea why, but it seems I pushed a different URL on my plugin that what the `raw` button provides.

What it is: `https://github.com/sum01/fmt-micro/raw/master/repo.json`
What it should be: `https://raw.githubusercontent.com/sum01/fmt-micro/master/repo.json`

Not actually sure if that matters, but it's the first thing that caught my eye.
EDIT: It seems that the current URL does prevent the fetch call, which is the issue. I'll push a fix.
